repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["src","--config-file=mypy.ini"]
        language: system
        pass_filenames: false
        exclude: ^(src/shared/path.py|src/shared/environment.py)$