name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest
      
      - name: Package API
        run: |
          cd ./venv/lib/python3.12/site-packages
          zip -r9 ../../../../api.zip .
          cd ../../../../api
          zip -g ../api.zip -r .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip

